### ISSUE TITLE
Complex i handling in pauli rotation commuting

### ISSUE THREAD

**Issue by gwwatkin** [alexnguyenn/lattice-surgery-compiler#28]
In applying the transformation:
![Screenshot_20210226_092442](https://user-images.githubusercontent.com/36427091/109333571-77d41980-7814-11eb-8cc8-ab6bcf3e04dd.png)
i.e.
![Screenshot_20210226_092506](https://user-images.githubusercontent.com/36427091/109333621-85899f00-7814-11eb-9b07-4d80c308661d.png)

when evaluating the tensor product of Pauli operators `PP'`:

![Screenshot_20210226_093047](https://user-images.githubusercontent.com/36427091/109334253-5889bc00-7815-11eb-80da-6f18c85aa58e.png)

We want to replace each `P_k P'_k` with another Pauli operator, which may be multiplied by an imaginary unit (eg. `XZ=Yi`). 

**Problem:** When `P_k` and `P'_k` are distinct and not identity, imaginary units are being discarded.

**Idea:**  in:

https://github.com/alexnguyenn/lattice-surgery-compiler/blob/b27de96165d71f7a76e636c74968ddfacca0dbf7/rotation.py#L36

Change the return to `-> Tuple[PauliOperator, complex]`

The complex number is a coefficient. For this function it will always be either `1` or `complex("j")` (`i` for common mortals).

https://github.com/alexnguyenn/lattice-surgery-compiler/blob/b27de96165d71f7a76e636c74968ddfacca0dbf7/circuit.py#L119

Multiply the complex coefficients together (including the one in the formula), giving a single `c` in front of a tensor product of pauli operators to go in the exponent.  `c` has to be one of `1,-1,complex("j"),-complex("j")`

For `c=1,-1` nothing happens or the angle is adjusted. The challenge is with `complex("j"),-complex("j")`

**Comment by gwwatkin** [comment]
![FF60238F-9AE1-4393-8312-0DF327E4EAF0](https://user-images.githubusercontent.com/36427091/109297770-d4dec800-7832-11eb-8ead-406cde8b7e6e.png)

**Comment by gwwatkin** [comment]
Conjecture `c=complex("j"),-complex("j")` never happens when.

**Comment by gwwatkin** [comment]
![B38241AF-300A-46E5-9480-05A46F45A88C](https://user-images.githubusercontent.com/36427091/109298535-099f4f00-7834-11eb-8694-c083328b1ec6.png)

**Comment by gwwatkin** [comment]
![EB3FB809-7362-4999-898B-9EA78BD738AF](https://user-images.githubusercontent.com/36427091/109298863-82061000-7834-11eb-8ef4-16c8045c2c05.png)

**Correction 2020-12-01:** The last line has an extra `-` sign, the final operator should be positive.

**Comment by gwwatkin** [comment]
@alexnguyenn  The argument from the point of view of `Circuit.commute_rotation`. Essentially as long as `P` and `P'` commute, c will never be `+i` or `-i`. In the above example c=-1.

**Proof:** If P and P' anticommute there have to be an odd number of anticommuting pairs of Pauli operators between them (qubits 1,4 and 5 in the example). Call `2k+1` this number. Factoring each `i`  out of the expanded tensor product (second to last line in the example) we get a global `i^(2k+1)=i*(-1)^k` factor.  The `i` in the factor _"reals out"_ with the `i` in `iPP'` leaving the global coefficient always real.

**Comment by gwwatkin** [comment]
It sounds to me like the easiest solution is to count how many times `Circuit.commute_rotation` detects an `i`, by checking the second returned value, and then counting.

Essentially the only difference with what we have now is that sometime we have to flip the angle to negative, when `iPP'` has a global `c=-1` coefficient.

**Comment by gwwatkin** [comment]
Forked the issue of the negative case to #30

**Comment by alexnguyenn** [comment]
Closed since the original problem is already handled in #29.
