### ISSUE TITLE
Handle the commuting of -pi/4 rotations when rotations exponent anti commute

### ISSUE THREAD

**Issue by gwwatkin** [alexnguyenn/lattice-surgery-compiler#30]
When `PP'=-P'P`, need to find out if this identity holds:
![Screenshot_20210301_013749](https://user-images.githubusercontent.com/36427091/109479200-02906080-7a2f-11eb-8dc4-0d534595877e.png)
Or how to best commute `-pi/4` rotations past other angles. For example it might be that the best way is to convert a `-pi/4` rotation into 7 `pi/4`s and then commute them one by one with the known identity
![Screenshot_20210226_092442](https://user-images.githubusercontent.com/36427091/109333571-77d41980-7814-11eb-8cc8-ab6bcf3e04dd.png)
i.e.
![Screenshot_20210226_092506](https://user-images.githubusercontent.com/36427091/109333621-85899f00-7814-11eb-9b07-4d80c308661d.png)

Then this needs to be implemented in `circuit.py`.

This issue was raised while working on #28.

**Comment by alexnguyenn** [comment]
**Example of commuting a -pi/4 rotation (P) from Litinski:**

Before:
![image](https://user-images.githubusercontent.com/46719079/109484815-bbf23480-7a35-11eb-9cde-8d56cdcba5fa.png)

After:
![image](https://user-images.githubusercontent.com/46719079/109484926-e217d480-7a35-11eb-981e-e14e1b42628f.png)

[Source for images](www.youtube.com/watch?v=TBJx89yocY8)

**Comment by gwwatkin** [comment]
The minus sign comes from here https://github.com/alexnguyenn/lattice-surgery-compiler/issues/28#issuecomment-786611605

**Comment by gwwatkin** [comment]
It seems that the rule is just to commute the the -pi/4 without any change.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/36427091/110318934-04c06500-7fc3-11eb-93b0-78696b6b6a43.png">

**Comment by alexnguyenn** [comment]
Also after taking a look at the above case, the minus signs for both the pi/8 and measurement came from iXZ = -Y. A new issue has been raised with regards to this #33.

**Comment by alexnguyenn** [comment]
Problem closed via #33
